name: Build

on:
  push:
  pull_request:

env:
  CMAKEFLAGS_COMMON: -DCMAKE_BUILD_TYPE=Release -DBATTERY=ON -DBROADCAST=ON -DBULK=ON -DDEBUG_ASSERTIONS_FATAL=ON -DHID=ON -DLILV=ON -DOPUS=ON -DQTKEYCHAIN=ON -DVINYLCONTROL=ON

jobs:
  build-ubuntu-gcc:
    name: Ubuntu 18.04 (gcc)
    runs-on: ubuntu-18.04
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Install build dependencies
      run: |
        sudo apt-get update && sudo apt-get install -y --no-install-recommends \
          ccache \
          libavformat-dev \
          libchromaprint-dev \
          libebur128-dev \
          libfaad-dev \
          libfftw3-dev \
          libflac-dev \
          libid3tag0-dev \
          liblilv-dev \
          libmad0-dev \
          libmodplug-dev \
          libmp3lame-dev \
          libmp4v2-dev \
          libopus-dev \
          libopusfile-dev \
          libportmidi-dev \
          libprotobuf-dev \
          libqt5opengl5-dev \
          libqt5sql5-sqlite \
          libqt5svg5-dev \
          libqt5x11extras5-dev \
          librubberband-dev \
          libshout3-dev \
          libsndfile1-dev \
          libsoundtouch-dev \
          libsqlite3-dev \
          libtag1-dev \
          libupower-glib-dev \
          libusb-1.0-0-dev \
          libwavpack-dev \
          portaudio19-dev \
          protobuf-compiler \
          qt5-default \
          qt5keychain-dev \
          qtscript5-dev \

    - name: Set up cmake
      uses: jwlawson/actions-setup-cmake@v1.4
      with:
        # This should always match the mininum required version in
        # our CMakeLists.txt
        cmake-version: '3.13.x'

    - name: Create build directory
      run: mkdir cmake_build
    - name: Set up ccache cache
      uses: actions/cache@v2
      with:
        path: ~/.ccache
        key: ${{ runner.os }}-ccache-${{ github.head_ref }}-${{ github.run_number }}
        restore-keys: |
          ${{ runner.os }}-ccache-${{ github.head_ref }}
          ${{ runner.os }}-ccache

    - name: Configure
      run: cmake $CMAKE_FLAGS_COMMON $CMAKE_FLAGS_UBUNTU -S . -B cmake_build
      env:
         # TODO for Ubuntu Focal: Replace "-DFAAD=ON" with "-DFFMPEG=ON"
         CMAKE_FLAGS_UBUNTU: -DFAAD=ON -DKEYFINDER=ON -DLOCALECOMPARE=ON -DMAD=ON -DMODPLUG=ON -DWAVPACK=ON

    - name: Set up problem matcher
      uses: ammaraskar/gcc-problem-matcher@master

    - name: Build
      run: cmake --build . -j $(nproc)
      working-directory: cmake_build

    - name: Test
      run: ctest --timeout 45
      working-directory: cmake_build
      env:
        GTEST_COLOR: 1
        CTEST_OUTPUT_ON_FAILURE: 1
        # Render analyzer waveform tests to an offscreen buffer
        QT_QPA_PLATFORM: offscreen

    - name: Package
      run: cpack -G DEB
      working-directory: cmake_build

    - name: Deploy artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Ubuntu DEB
        path: cmake_build/*.deb

  build-mac:
    name: macOS 10.15
    runs-on: macos-10.15
    env:
      APPLE_CODESIGN_IDENTITY: 2C2B5D3EDCE82BA55E22E9A67F16F8D03E390870
    steps:
    - name: clone Git repository
      uses: actions/checkout@v2

    - name: ccache
      uses: actions/cache@v2
      with:
        path: /Users/runner/Library/Caches/ccache
        key: ${{ runner.os }}-ccache-${{ github.head_ref }}-${{ github.run_number }}
        restore-keys: |
          ${{ runner.os }}-ccache-${{ github.head_ref }}
          ${{ runner.os }}-ccache

    - name: read build environment file
      id: buildenv_name
      run: tools/macos_buildenv.sh name --ghactions

    - name: macOS build environment cache
      uses: actions/cache@v2
      env:
        cache-name: macOS build environment
      with:
        path: /Users/runner/buildenv
        key: macOS-build-environment-${{ steps.buildenv_name.outputs.name }}

    - name: Import code signing identity
      env:
        MACOS_CODESIGN_OPENSSL_PASSWORD: ${{ secrets.MACOS_CODESIGN_OPENSSL_PASSWORD }}
        MACOS_CODESIGN_CERTIFICATE_PASSWORD: ${{ secrets.MACOS_CODESIGN_CERTIFICATE_PASSWORD }}
      run: |
        if [ -n "$MACOS_CODESIGN_OPENSSL_PASSWORD" ] && [ -n "$MACOS_CODESIGN_CERTIFICATE_PASSWORD" ]; then
          # Decrypt the certificate
          openssl enc -aes-256-cbc -d -md sha512 \
            -k ${MACOS_CODESIGN_OPENSSL_PASSWORD} \
            -in /Users/runner/work/mixxx/mixxx/cmake/macos_developer_id_codesign_certificate.p12.enc \
            -out ~/certificate.p12

          # Create a temporary keychain for the certificate and import it.
          security create-keychain -p mixxx Mixxx.keychain
          security unlock-keychain -p mixxx Mixxx.keychain
          security import ~/certificate.p12 -k Mixxx.keychain \
            -P ${MACOS_CODESIGN_CERTIFICATE_PASSWORD} -T /usr/bin/codesign
          security set-key-partition-list -S apple-tool:,apple: -k mixxx Mixxx.keychain
          # Add keychain to search list
          security list-keychains -s Mixxx.keychain

          CMAKE_ARGS="-DAPPLE_CODESIGN_IDENTITY=${APPLE_CODESIGN_IDENTITY}"
        fi
        echo "::set-output name=cmake_args::${CMAKE_ARGS}"

    - name: Set up macOS build environment
      id: buildenv
      run: tools/macos_buildenv.sh setup --ghactions

    - name: Set up ccache
      run: ccache -M 5G
      env:
        PATH: ${{ steps.buildenv.outputs.path }}

    - name: Create build directory
      run: mkdir cmake_build

    - name: Configure
      run: cmake -L $CMAKE_FLAGS_COMMON $CMAKE_FLAGS_MAC ..
      working-directory: cmake_build
      env:
        CMAKE_FLAGS_MAC: -DCOREAUDIO=ON -DHSS1394=ON -DMACOS_BUNDLE=ON ${{ steps.buildenv.outputs.cmake_args }} ${{ steps.apple_codesign.outputs.cmake_args }} -DCMAKE_PREFIX_PATH=${{ steps.buildenv.outputs.cmake_prefix_path }} -DQt5_DIR=${{ steps.buildenv.outputs.qt_path }}
        PATH: ${{ steps.buildenv.outputs.path }}
        MACOSX_DEPLOYMENT_TARGET: ${{ steps.buildenv.outputs.macosx_deployment_target }}

    - name: Build
      run: cmake --build . -j $(sysctl -n hw.physicalcpu)
      working-directory: cmake_build
      env:
        # GitHub Actions automatically zstd compresses caches
        CCACHE_NOCOMPRESS: true
        PATH: ${{ steps.buildenv.outputs.path }}

    - name: Print ccache stats
      run: ccache -s
      env:
        PATH: ${{ steps.buildenv.outputs.path }}

    - name: Test
      run: ctest --timeout 45 --exclude-regex DirectoryDAOTest.relocateDirectory
      working-directory: cmake_build
      env:
        PATH: ${{ steps.buildenv.outputs.path }}
        QT_QPA_PLATFORM_PLUGIN_PATH: ${{ steps.buildenv.outputs.qt_qpa_platform_plugin_path }}
        GTEST_COLOR: 1
        CTEST_OUTPUT_ON_FAILURE: 1
        # Render analyzer waveform tests to an offscreen buffer
        QT_QPA_PLATFORM: offscreen

    - name: Benchmark
      run: cmake --build . --target mixxx-benchmark
      working-directory: cmake_build

    - name: Package
      run: |
        cpack -G DragNDrop
        if [ -n "$MACOS_CODESIGN_OPENSSL_PASSWORD" ] && [ -n "$MACOS_CODESIGN_CERTIFICATE_PASSWORD" ]; then
          codesign --verbose=4 --deep --force --options runtime \
            --sign $APPLE_CODESIGN_IDENTITY \
            --entitlements ../build/osx/entitlements.plist *.dmg
        fi
      working-directory: cmake_build
      env:
        PATH: ${{ steps.buildenv.outputs.path }}

    - name: Deploy artifacts
      uses: actions/upload-artifact@v2
      with:
        name: macOS-DMG
        path: cmake_build/*.dmg
