name: pre-commit-pr

on:
  pull_request:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - name: Install clang-format
      run: sudo apt-get update && sudo apt-get install -y --no-install-recommends clang-format-10
    - uses: pre-commit/action@v2.0.0
      # HEAD is the not yet integrated PR merge commit +refs/pull/xxxx/merge
      # HEAD^1 is the PR target branch and HEAD^2 is the HEAD of the source branch
      extra_args: --from-ref HEAD^1 --to-ref HEAD
